import React, { Component } from "react";
import { ScrollView, useWindowDimensions } from "react-native";
import HTML from "react-native-render-html";

const htmlContent = `
<p class="Normal">Theo đại diện Bộ Y tế, đến nay vaccine Astra Zeneca vẫn đảm bảo an to&agrave;n, n&ecirc;n Bộ sẽ đẩy nhanh tiến độ ti&ecirc;m theo thứ tự ưu ti&ecirc;n trong&nbsp;<a href="https://vnexpress.net/nguoi-tham-gia-chong-covid-19-duoc-uu-tien-tiem-vaccine-4240639.html" rel="dofollow">Nghị quyết 21 của Ch&iacute;nh phủ</a>; hướng dẫn của Bộ Y tế về tiếp nhận, bảo quản, ph&acirc;n phối v&agrave; sử dụng vaccine.</p>
<p class="Normal">Đại diện Bộ Y tế cũng cho hay thế giới đang c&oacute; hiện tượng vaccine cung cấp kh&ocirc;ng đủ mua v&agrave; c&aacute;c nước ở trong "cuộc đua tranh khốc liệt". Do đ&oacute;, Việt Nam phải cố gắng hết sức để c&oacute; vaccine sớm nhất.</p>
<p class="Normal">Bộ trưởng Y tế Nguyễn Thanh Long n&oacute;i đ&atilde; nảy sinh những kh&oacute; khăn, vướng mắc mới trong tiếp cận, đ&agrave;m ph&aacute;n mua c&aacute;c nguồn vaccine, thậm ch&iacute; "phải chấp nhận rủi ro mới tiếp cận được nguồn".</p>
<figure class="tplCaption action_thumb_added" data-size="true">
<div class="fig-picture"><picture><source srcset="https://i1-vnexpress.vnecdn.net/2021/04/14/Vaccine-HuuKhoa-2-1615168279-j-5206-6818-1618392399.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=24WfdmCBTKUcVPD9BWr2hw 1x, https://i1-vnexpress.vnecdn.net/2021/04/14/Vaccine-HuuKhoa-2-1615168279-j-5206-6818-1618392399.jpg?w=1020&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=W4MpGpAiuZn1V1q9fAssmQ 1.5x, https://i1-vnexpress.vnecdn.net/2021/04/14/Vaccine-HuuKhoa-2-1615168279-j-5206-6818-1618392399.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=2&amp;fit=crop&amp;s=uSLBjGuFfit6fu8rLI9WoA 2x" data-srcset="https://i1-vnexpress.vnecdn.net/2021/04/14/Vaccine-HuuKhoa-2-1615168279-j-5206-6818-1618392399.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=24WfdmCBTKUcVPD9BWr2hw 1x, https://i1-vnexpress.vnecdn.net/2021/04/14/Vaccine-HuuKhoa-2-1615168279-j-5206-6818-1618392399.jpg?w=1020&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=W4MpGpAiuZn1V1q9fAssmQ 1.5x, https://i1-vnexpress.vnecdn.net/2021/04/14/Vaccine-HuuKhoa-2-1615168279-j-5206-6818-1618392399.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=2&amp;fit=crop&amp;s=uSLBjGuFfit6fu8rLI9WoA 2x" /><img class="lazy lazied" src="https://i1-vnexpress.vnecdn.net/2021/04/14/Vaccine-HuuKhoa-2-1615168279-j-5206-6818-1618392399.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=24WfdmCBTKUcVPD9BWr2hw" alt="Nh&acirc;n vi&ecirc;n y tế Bệnh viện Bệnh Nhiệt đới TP HCM kiểm tra lọ vaccine AstraZeneca trước khi bắt đầu ti&ecirc;m chủng ng&agrave;y 8/3. Ảnh: Hữu Khoa" data-src="https://i1-vnexpress.vnecdn.net/2021/04/14/Vaccine-HuuKhoa-2-1615168279-j-5206-6818-1618392399.jpg?w=680&amp;h=0&amp;q=100&amp;dpr=1&amp;fit=crop&amp;s=24WfdmCBTKUcVPD9BWr2hw" data-ll-status="loaded" /></picture></div>
<figcaption>
<p class="Image">Nh&acirc;n vi&ecirc;n y tế Bệnh viện Bệnh Nhiệt đới TP HCM kiểm tra lọ vaccine AstraZeneca trước khi bắt đầu ti&ecirc;m chủng ng&agrave;y 8/3. Ảnh:&nbsp;<em>Hữu Khoa</em></p>
</figcaption>
</figure>
<p class="Normal"><strong>Về việc thử nghiệm vaccine Covid-19 trong nước</strong>, Trung tướng, GS Đỗ Quyết, Gi&aacute;m đốc Học viện Qu&acirc;n y (Bộ Quốc ph&ograve;ng), cho biết ng&agrave;y mai (15/4) sẽ kết th&uacute;c lấy mẫu m&aacute;u người ti&ecirc;m thử nghiệm giai đoạn hai vaccine Nano Covax tại hai điểm l&agrave; Học viện Qu&acirc;n y v&agrave; Viện Pasteur TP HCM.</p>
<p class="Normal">Dự kiến đầu th&aacute;ng 5/2021, Học viện Qu&acirc;n y sẽ b&aacute;o c&aacute;o Bộ Y tế v&agrave; Hội đồng Đạo đức trong nghi&ecirc;n cứu y sinh học quốc gia xem x&eacute;t, đ&aacute;nh gi&aacute; c&aacute;c cơ sở khoa học của giai đoạn hai, cho ph&eacute;p x&acirc;y dựng một liều ti&ecirc;m; sau đ&oacute; vừa ho&agrave;n thiện giai đoạn hai, vừa ti&ecirc;m giai đoạn ba.</p>
<p class="Normal">GS Đỗ Quyết cũng th&ocirc;ng b&aacute;o, trong số 554 t&igrave;nh nguyện vi&ecirc;n (6 người r&uacute;t khỏi đợt thử nghiệm), sau khi ti&ecirc;m mũi hai (giai đoạn hai) Nano Covax, c&aacute;c t&igrave;nh nguyện vi&ecirc;n c&oacute; triệu chứng sốt nhẹ, đau chỗ ti&ecirc;m, cơ, khớp, mệt mỏi... nhưng hết nhanh, kh&ocirc;ng cần can thiệp y tế. "Đến nay, sức khỏe c&aacute;c t&igrave;nh nguyện vi&ecirc;n đều ổn định, vaccine Nano Covax an to&agrave;n với người được ti&ecirc;m, kh&aacute;ng thể tăng cao, khả năng trung h&ograve;a virus tốt", Trung tướng Đỗ Quyết n&oacute;i v&agrave; đề nghị c&aacute;c cơ quan ủng hộ, hỗ trợ nhiều hơn nữa qu&aacute; tr&igrave;nh nghi&ecirc;n cứu, sản xuất vaccine Covid-19 trong nước.</p>
<p class="Normal">Ban chỉ đạo cho rằng, d&acirc;n số Việt Nam 100 triệu người, n&ecirc;n cần tiếp tục đẩy nhanh, tạo mọi điều kiện cho c&aacute;c đơn vị thử nghiệm l&acirc;m s&agrave;ng vaccine ph&ograve;ng Covid-19; chuẩn bị phương &aacute;n đầu tư, sản xuất nếu thử nghiệm th&agrave;nh c&ocirc;ng.</p>
<p class="Normal">Thời gian tới, c&aacute;c bộ Y tế, C&ocirc;ng an, Quốc ph&ograve;ng đề nghị tiếp tục siết chặt kiểm so&aacute;t người nhập cảnh trong khi đợi ch&iacute;nh s&aacute;ch về "hộ chiếu vaccine", bởi dịch bệnh tr&ecirc;n thế giới đang tăng trở lại. Việt Nam sẽ tiếp tục thực hiện cơ chế tổ c&ocirc;ng t&aacute;c gồm đại diện 5 bộ (Y tế, Ngoại giao, Quốc ph&ograve;ng, Giao th&ocirc;ng Vận tải), để điều phối c&aacute;c chuyến bay đưa chuy&ecirc;n gia nước ngo&agrave;i, lao động kỹ thuật cao nhập cảnh.</p>
<ul class="list-news gaBoxLinkDisplay" data-campaign="Box-Related" data-event-category="Article Link Display" data-event-action="Box-Related" data-event-label="Item-0" data-gtm-vis-first-on-screen-2359946_230="11554" data-gtm-vis-total-visible-time-2359946_230="100" data-gtm-vis-has-fired-2359946_230="1">
<li data-id="4260696"><a title="'Việt Nam c&oacute; thể tự sản xuất vaccine Covid-19 trong th&aacute;ng 8'" href="https://vnexpress.net/viet-nam-co-the-tu-san-xuat-vaccine-covid-19-trong-thang-8-4260696.html" data-medium="Item-1" data-event-category="Article Link Click" data-event-action="Box-Related" data-event-label="1" data-itm-source="#vn_source=Detail&amp;vn_campaign=Box-Related&amp;vn_medium=Item-1&amp;vn_term=Desktop" data-itm-added="1">'Việt Nam c&oacute; thể tự sản xuất vaccine Covid-19 trong th&aacute;ng 8'</a><span class="meta-news"><a class="count_cmt" href="https://vnexpress.net/viet-nam-co-the-tu-san-xuat-vaccine-covid-19-trong-thang-8-4260696.html#box_comment_vne" data-event-category="Article Link Click" data-event-action="Box-Related" data-event-label="1" data-itm-source="#vn_source=Detail&amp;vn_campaign=Box-Related&amp;vn_medium=Item-1&amp;vn_term=Desktop" data-itm-added="1">&nbsp;<span class="font_icon widget-comment-4260696-1">31</span></a></span></li>
<li data-id="4259058"><a title="Việt Nam đặt mục ti&ecirc;u c&oacute; đủ vaccine Covid-19 từ năm 2022" href="https://vnexpress.net/viet-nam-dat-muc-tieu-co-du-vaccine-covid-19-tu-nam-2022-4259058.html" data-medium="Item-2" data-event-category="Article Link Click" data-event-action="Box-Related" data-event-label="2" data-itm-source="#vn_source=Detail&amp;vn_campaign=Box-Related&amp;vn_medium=Item-2&amp;vn_term=Desktop" data-itm-added="1">Việt Nam đặt mục ti&ecirc;u c&oacute; đủ vaccine Covid-19 từ năm 2022</a><span class="meta-news"><a class="count_cmt" href="https://vnexpress.net/viet-nam-dat-muc-tieu-co-du-vaccine-covid-19-tu-nam-2022-4259058.html#box_comment_vne" data-event-category="Article Link Click" data-event-action="Box-Related" data-event-label="2" data-itm-source="#vn_source=Detail&amp;vn_campaign=Box-Related&amp;vn_medium=Item-2&amp;vn_term=Desktop" data-itm-added="1">&nbsp;<span class="font_icon widget-comment-4259058-1">17</span></a></span></li>
<li data-id="4256596"><a title="Bộ Y tế được cấp hơn 1.200 tỷ đồng mua vaccine Covid-19" href="https://vnexpress.net/bo-y-te-duoc-cap-hon-1-200-ty-dong-mua-vaccine-covid-19-4256596.html" data-medium="Item-3" data-event-category="Article Link Click" data-event-action="Box-Related" data-event-label="3" data-itm-source="#vn_source=Detail&amp;vn_campaign=Box-Related&amp;vn_medium=Item-3&amp;vn_term=Desktop" data-itm-added="1">Bộ Y tế được cấp hơn 1.200 tỷ đồng mua vaccine Covid-19</a></li>
<li data-id="4252331"><a title="Việt Nam dự kiến c&oacute; vaccine Covid-19 tự sản xuất v&agrave;o qu&yacute; 3" href="https://vnexpress.net/viet-nam-du-kien-co-vaccine-covid-19-tu-san-xuat-vao-quy-3-4252331.html" data-medium="Item-4" data-event-category="Article Link Click" data-event-action="Box-Related" data-event-label="4" data-itm-source="#vn_source=Detail&amp;vn_campaign=Box-Related&amp;vn_medium=Item-4&amp;vn_term=Desktop" data-itm-added="1">Việt Nam dự kiến c&oacute; vaccine Covid-19 tự sản xuất v&agrave;o qu&yacute; 3</a><span class="meta-news"><a class="count_cmt" href="https://vnexpress.net/viet-nam-du-kien-co-vaccine-covid-19-tu-san-xuat-vao-quy-3-4252331.html#box_comment_vne" data-event-category="Article Link Click" data-event-action="Box-Related" data-event-label="4" data-itm-source="#vn_source=Detail&amp;vn_campaign=Box-Related&amp;vn_medium=Item-4&amp;vn_term=Desktop" data-itm-added="1">&nbsp;<span class="font_icon widget-comment-4252331-1">54</span></a></span></li>
<li data-id="4240639"><a title="Người tham gia chống Covid-19 được ưu ti&ecirc;n ti&ecirc;m vaccine" href="https://vnexpress.net/nguoi-tham-gia-chong-covid-19-duoc-uu-tien-tiem-vaccine-4240639.html" data-medium="Item-5" data-event-category="Article Link Click" data-event-action="Box-Related" data-event-label="5" data-itm-source="#vn_source=Detail&amp;vn_campaign=Box-Related&amp;vn_medium=Item-5&amp;vn_term=Desktop" data-itm-added="1">Người tham gia chống Covid-19 được ưu ti&ecirc;n ti&ecirc;m vaccine</a></li>
</ul>
`;

export default function Demo() {
  const contentWidth = useWindowDimensions().width;
  return (
    <ScrollView style={{ flex: 1 }}>
        
      <HTML source={{ html: htmlContent }} contentWidth={contentWidth} />
    </ScrollView>
  );
}